[config]
schemaVersion = "0.0.1"

[package]
namespace = "madkarma"
name = "RicardoBracken"
versionNumber = "1.0.4"
description = "Get your neck snapped by a legend"
websiteUrl = "https://github.com/madkarmaa/RicardoBracken"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../build"


[[build.copy]]
source = "./madkarma.RicardoBracken.dll"
target = "./plugin/"

[[build.copy]]
source = "./models"
target = "./plugin/"

[[build.copy]]
source = "./audios"
target = "./plugin/"


[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "bepinex", "audio", "clientside", "mods", "monsters" ]